import React, { useRef } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/state-management/StoreProvider";
import { makeStore, AppStore } from "@/state-management/store";
import NotificationManager from "@/utils/NotificationManager/NotificationManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.StrictMode>
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}

            <NotificationManager />
          </body>
        </html>
      </StoreProvider>
    </React.StrictMode>
  );
}
