"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const react_1 = __importDefault(require("react"));
const google_1 = require("next/font/google");
require("./globals.css");
const StoreProvider_1 = __importDefault(require("@/state-management/StoreProvider"));
const NotificationManager_1 = __importDefault(require("@/utils/NotificationManager/NotificationManager"));
const AuthProvider_component_1 = __importDefault(require("@/utils/AuthManager/AuthProvider.component"));
const next_1 = require("next-auth/next");
const route_1 = require("@/app/api/auth/[...nextauth]/route");
const Header_component_1 = __importDefault(require("@/components/Header/Header.component"));
const inter = (0, google_1.Inter)({ subsets: ["latin"] });
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout(_a) {
    return __awaiter(this, arguments, void 0, function* ({ children, }) {
        const session = yield (0, next_1.getServerSession)(route_1.authOptions);
        return (<react_1.default.StrictMode>
      <AuthProvider_component_1.default>
        <StoreProvider_1.default session={session}>
          <html lang="en">
            <body className={inter.className}>
              <Header_component_1.default />
              {children}

              <NotificationManager_1.default />
            </body>
          </html>
        </StoreProvider_1.default>
      </AuthProvider_component_1.default>
    </react_1.default.StrictMode>);
    });
}
